### ISSUE TITLE
Opposite signal before stop loss

### ISSUE THREAD

**Issue by ElsiePop** [goncaloe/nnfx-backtest#7]
Hello,

What happens with this scenario:

"*You will find times where your indicator gave you a signal to go the other way before price had the chance to become a win or a loss.  Just chalk this up as nothing, and move on." (https://nononsenseforex.com/forex-q-and-a-podcast/forex-backtesting-step-by-step/)

Has this been coded?

Rgds.

**Comment by goncaloe** [comment]
you can use change the input "ReopenOnOppositeSignal" to count chalks or not.
