### ISSUE TITLE
What is the difference between Simple Win rate and Estimated Win Rate ?

### ISSUE THREAD

**Issue by hhajjali** [goncaloe/nnfx-backtest#8]
Hi,

Great thanks for this EA, very helpful. 
I have a question more than an issue: What is the difference between Simple win rate and Estimated Win Rate ?
Can you share the formula? 

I noticed when I chalk out indicator switch by choosing "ReopenOnOppositeSignal" = "False", both numbers are the same.

Thanks for your help.

**Comment by goncaloe** [comment]
wins or losses of opposite sinal only counts half
